"""Service for IMD, CWC & DGRE Himalayan Snowmelt Runoff,
Snow Cover Area (SCA) & Glacial Hydrology Engine (SNOWMELT-HYDRO).
"""

from datetime import datetime, timezone
from typing import Dict, List, Optional
from app.schemas.snowmelt_runoff import (
    BasinSummary,
    CatchmentRunoffMetrics,
    DownstreamHydropowerInflow,
    ElevationZonalBand,
    HydropowerInflowStatus,
    SnowCoverTier,
    SnowmeltBasin,
    SnowmeltRegime,
    SnowmeltRunoffResponse,
    SnowpackCryosphereTelemetry,
)


class SnowmeltRunoffService:
    """Calculates Martinec-Rango Snowmelt Runoff Model (SRM) dynamics,
    hypsometric elevation band snowmelt, freezing level isotherms,
    and downstream hydropower dam inflow telemetry.
    """

    _BASIN_REGISTRY: Dict[str, Dict] = {
        "satluj_bhakra": {
            "basin_id": "satluj_bhakra",
            "basin_name": "Satluj Basin & Bhakra Reservoir Catchment",
            "state": "Himachal Pradesh",
            "mountain_range": "Western Himalaya (Pir Panjal & Great Himalaya)",
            "drainage_area_sq_km": 56874.0,
            "current_regime": SnowmeltRegime.SEASONAL_SNOWMELT_SURGE,
            "elevation_bands": [
                {
                    "band_id": "ZONE_A",
                    "elevation_range_label": "1,500m - 2,500m AMSL (Lower Valley)",
                    "elevation_min_m": 1500.0,
                    "elevation_max_m": 2500.0,
                    "zonal_area_sq_km": 8530.0,
                    "snow_cover_area_pct": 12.0,
                    "mean_temperature_c": 16.5,
                    "degree_day_factor_cm_per_deg_c_day": 0.38,
                    "daily_melt_volume_mcm": 6.4,
                },
                {
                    "band_id": "ZONE_B",
                    "elevation_range_label": "2,500m - 3,500m AMSL (Mid-Elevation Snowpack)",
                    "elevation_min_m": 2500.0,
                    "elevation_max_m": 3500.0,
                    "zonal_area_sq_km": 14220.0,
                    "snow_cover_area_pct": 52.0,
                    "mean_temperature_c": 10.2,
                    "degree_day_factor_cm_per_deg_c_day": 0.48,
                    "daily_melt_volume_mcm": 36.2,
                },
                {
                    "band_id": "ZONE_C",
                    "elevation_range_label": "3,500m - 4,500m AMSL (Sub-Glacial Firn Zone)",
                    "elevation_min_m": 3500.0,
                    "elevation_max_m": 4500.0,
                    "zonal_area_sq_km": 18200.0,
                    "snow_cover_area_pct": 84.0,
                    "mean_temperature_c": 4.8,
                    "degree_day_factor_cm_per_deg_c_day": 0.62,
                    "daily_melt_volume_mcm": 45.5,
                },
                {
                    "band_id": "ZONE_D",
                    "elevation_range_label": "> 4,500m AMSL (Perpetual Cryosphere & Glaciers)",
                    "elevation_min_m": 4500.0,
                    "elevation_max_m": 6800.0,
                    "zonal_area_sq_km": 15924.0,
                    "snow_cover_area_pct": 96.0,
                    "mean_temperature_c": -1.2,
                    "degree_day_factor_cm_per_deg_c_day": 0.75,
                    "daily_melt_volume_mcm": 14.8,
                },
            ],
            "cryosphere_telemetry": {
                "snow_line_altitude_m": 3250.0,
                "equilibrium_line_altitude_m": 4750.0,
                "freezing_level_isotherm_m": 4620.0,
                "basin_snow_water_equivalent_mm": 285.0,
                "fresh_snow_24h_cm": 0.0,
                "satellite_ndsi_coverage_pct": 94.5,
            },
            "runoff_metrics": {
                "daily_discharge_cumecs": 1420.0,
                "snowmelt_fraction_pct": 64.5,
                "rainfall_contribution_pct": 18.5,
                "baseflow_contribution_pct": 17.0,
                "peak_diurnal_hour_ist": "18:00 IST",
                "peak_diurnal_discharge_cumecs": 1780.0,
                "diurnal_discharge_amplitude_pct": 42.0,
            },
            "hydropower_inflows": [
                {
                    "dam_name": "Bhakra Dam (Gobind Sagar)",
                    "river_basin": "Satluj River Basin",
                    "installed_capacity_mw": 1325.0,
                    "live_inflow_cumecs": 1340.0,
                    "generation_capacity_utilized_pct": 92.0,
                    "daily_storage_gain_mcm": 84.5,
                    "spillway_clearance_margin_m": 8.4,
                    "inflow_status": HydropowerInflowStatus.OPTIMAL_GENERATION_SURGE,
                },
                {
                    "dam_name": "Nathpa Jhakri Hydroelectric Plant",
                    "river_basin": "Upper Satluj Gorge",
                    "installed_capacity_mw": 1500.0,
                    "live_inflow_cumecs": 1180.0,
                    "generation_capacity_utilized_pct": 98.0,
                    "daily_storage_gain_mcm": 12.0,
                    "spillway_clearance_margin_m": 4.2,
                    "inflow_status": HydropowerInflowStatus.OPTIMAL_GENERATION_SURGE,
                },
            ],
            "riparian_safety_advisory": "Late-afternoon diurnal snowmelt peak between 17:00 and 20:00 IST. Downstream riverbed activities, fishing, and unregulated bathing prohibited along Satluj gorge from Rampur Bushahr to Bilaspur.",
            "vernacular_bulletins": {
                "en": "IMD-CWC SATLUJ SNOWMELT BULLETIN: Diurnal snowmelt discharge surge active in Zone B & C (2,500m-4,500m) with total river inflow of 1,420 cumecs at Bhakra Reservoir. Gobind Sagar storage filling rapidly (+84.5 MCM/day). Downstream riverbed warning in effect for late afternoon hours.",
                "hi": "आईएमडी-सीडब्ल्यूसी सतलुज हिमद्रवण बुलेटिन: 2,500 से 4,500 मीटर की ऊंचाई पर बर्फ पिघलने की दर तेज है। भाखड़ा जलाशय में 1,420 क्यूमेक का कुल जलप्रवाह दर्ज किया गया है। गोविंद सागर में दैनिक 84.5 एमसीएम पानी जमा हो रहा है। शाम 5 से 8 बजे के बीच नदी किनारे न जाएं।",
                "pa": "ਸਤਲੁਜ ਬੇਸਿਨ ਬਰਫ਼ ਪਿਘਲਣ ਬੁਲੇਟਿਨ: 2,500-4,500 ਮੀਟਰ ਉਚਾਈ 'ਤੇ ਤੇਜ਼ੀ ਨਾਲ ਬਰਫ਼ ਪਿਘਲਣ ਕਾਰਨ ਭਾਖੜਾ ਡੈਮ ਵਿੱਚ 1,420 ਕਿਊਮਿਕ ਪਾਣੀ ਆ ਰਿਹਾ ਹੈ। ਗੋਬਿੰਦ ਸਾਗਰ ਝੀਲ ਤੇਜ਼ੀ ਨਾਲ ਭਰ ਰਹੀ ਹੈ। ਸ਼ਾਮ ਵੇਲੇ ਦਰਿਆ ਕੰਢੇ ਜਾਣ ਤੋਂ ਗੁਰੇਜ਼ ਕਰੋ।",
                "ne": "सतलुज जलाधार हिउँ पग्लने चेतावनी: उच्च हिमाली क्षेत्रमा तापक्रम वृद्धिसँगै भाखड़ा जलाशयमा १४२० क्युमेक जलप्रवाह पुगेको छ। साँझको समयमा नदी तटीय क्षेत्रमा नजानुहोला।",
                "ks": "ستلج سنو میلٹ بلیٹن: بھاکھڑا ڈیمس منز چھُ 1,420 کیومکس آب جمع گژھان۔ شامن پیٹھہٕ کٔنٛڈؠن ترٛاونہٕ نش پرہیز کٔرِو۔",
                "bn": "শতদ্রু অববাহিকা তুষারগলন বুলেটিন: উচ্চ হিমালয়ে তীব্র তুষারগলনের ফলে ভাকরা জলাধারে ১৪২০ কিউমেক জলপ্রবাহ রেকর্ড করা হয়েছে। নদী তীরবর্তী অঞ্চলে বিকেলে সতর্কতা জারি।",
                "bo": "གཙང་པོ་སཏ་ལུཇ་གི་ཁངས་ཞུ་བའི་ཉེན་བརྡ། བྷཀྲ་རགས་ཆེན་དུ་ཆུ་རྒྱུན་ཤུགས་ཆེན་འབབ་བཞིན་ཡོད། དགོང་མོའི་དུས་སུ་ཆུ་འགྲམ་དུ་མ་འགྲོ།",
            },
        },
        "bhagirathi_tehri": {
            "basin_id": "bhagirathi_tehri",
            "basin_name": "Bhagirathi & Alaknanda Basin (Tehri Dam Catchment)",
            "state": "Uttarakhand",
            "mountain_range": "Garhwal Himalaya",
            "drainage_area_sq_km": 7511.0,
            "current_regime": SnowmeltRegime.GLACIAL_ABLATION_PEAK,
            "elevation_bands": [
                {
                    "band_id": "ZONE_A",
                    "elevation_range_label": "1,000m - 2,500m AMSL (Tehri Valley)",
                    "elevation_min_m": 1000.0,
                    "elevation_max_m": 2500.0,
                    "zonal_area_sq_km": 1650.0,
                    "snow_cover_area_pct": 0.0,
                    "mean_temperature_c": 19.2,
                    "degree_day_factor_cm_per_deg_c_day": 0.40,
                    "daily_melt_volume_mcm": 0.0,
                },
                {
                    "band_id": "ZONE_B",
                    "elevation_range_label": "2,500m - 3,800m AMSL (Sub-Alpine Forest & Meadows)",
                    "elevation_min_m": 2500.0,
                    "elevation_max_m": 3800.0,
                    "zonal_area_sq_km": 2180.0,
                    "snow_cover_area_pct": 34.0,
                    "mean_temperature_c": 9.5,
                    "degree_day_factor_cm_per_deg_c_day": 0.52,
                    "daily_melt_volume_mcm": 11.5,
                },
                {
                    "band_id": "ZONE_C",
                    "elevation_range_label": "3,800m - 5,000m AMSL (Glacial Snout & Moraines)",
                    "elevation_min_m": 3800.0,
                    "elevation_max_m": 5000.0,
                    "zonal_area_sq_km": 2450.0,
                    "snow_cover_area_pct": 78.0,
                    "mean_temperature_c": 4.1,
                    "degree_day_factor_cm_per_deg_c_day": 0.72,
                    "daily_melt_volume_mcm": 22.8,
                },
                {
                    "band_id": "ZONE_D",
                    "elevation_range_label": "> 5,000m AMSL (Gangotri & Khatling Icefield Peaks)",
                    "elevation_min_m": 5000.0,
                    "elevation_max_m": 7138.0,
                    "zonal_area_sq_km": 1231.0,
                    "snow_cover_area_pct": 98.0,
                    "mean_temperature_c": -2.5,
                    "degree_day_factor_cm_per_deg_c_day": 0.85,
                    "daily_melt_volume_mcm": 4.2,
                },
            ],
            "cryosphere_telemetry": {
                "snow_line_altitude_m": 3950.0,
                "equilibrium_line_altitude_m": 5100.0,
                "freezing_level_isotherm_m": 4850.0,
                "basin_snow_water_equivalent_mm": 210.0,
                "fresh_snow_24h_cm": 0.0,
                "satellite_ndsi_coverage_pct": 96.0,
            },
            "runoff_metrics": {
                "daily_discharge_cumecs": 890.0,
                "snowmelt_fraction_pct": 58.0,
                "rainfall_contribution_pct": 24.0,
                "baseflow_contribution_pct": 18.0,
                "peak_diurnal_hour_ist": "17:30 IST",
                "peak_diurnal_discharge_cumecs": 1150.0,
                "diurnal_discharge_amplitude_pct": 38.5,
            },
            "hydropower_inflows": [
                {
                    "dam_name": "Tehri Dam Hydro Complex",
                    "river_basin": "Bhagirathi River",
                    "installed_capacity_mw": 2400.0,
                    "live_inflow_cumecs": 845.0,
                    "generation_capacity_utilized_pct": 88.0,
                    "daily_storage_gain_mcm": 52.0,
                    "spillway_clearance_margin_m": 12.5,
                    "inflow_status": HydropowerInflowStatus.NORMAL_STORAGE_FILL,
                },
                {
                    "dam_name": "Koteshwar Dam",
                    "river_basin": "Bhagirathi Lower Reach",
                    "installed_capacity_mw": 400.0,
                    "live_inflow_cumecs": 790.0,
                    "generation_capacity_utilized_pct": 95.0,
                    "daily_storage_gain_mcm": 6.5,
                    "spillway_clearance_margin_m": 5.8,
                    "inflow_status": HydropowerInflowStatus.OPTIMAL_GENERATION_SURGE,
                },
            ],
            "riparian_safety_advisory": "Gangotri and Khatling glacial ablation surge. Water level in Bhagirathi gorge between Gangnanai and Uttarkashi fluctuates rapidly from 16:30 onwards. Char Dham pilgrims advised not to venture to riverbanks.",
            "vernacular_bulletins": {
                "en": "TEHRI DAM GLACIAL HYDROLOGY BULLETIN: Active glacial ablation in Gangotri basin generating 890 cumecs inflow into Tehri Lake. Storage filling steadily. Char Dham pilgrims warned against riverbed halt in upper Bhagirathi valley.",
                "hi": "टिहरी बांध हिमनद जलविज्ञान बुलेटिन: गंगोत्री ग्लेशियर से बर्फ व हिमनद पिघलने से टिहरी झील में 890 क्यूमेक प्रवाह जारी है। चारधाम तीर्थयात्री शाम के समय भागीरथी नदी के घाटों से दूर रहें।",
                "pa": "ਟਿਹਰੀ ਡੈਮ ਗਲੇਸ਼ੀਅਰ ਪਾਣੀ ਬੁਲੇਟਿਨ: ਗੰਗੋਤਰੀ ਗਲੇਸ਼ੀਅਰ ਤੋਂ ਤੇਜ਼ੀ ਨਾਲ ਪਾਣੀ ਆਉਣ ਕਾਰਨ ਟਿਹਰੀ ਝੀਲ ਵਿੱਚ 890 ਕਿਊਮਿਕ ਪਾਣੀ ਦਰਜ ਕੀਤਾ ਗਿਆ। ਯਾਤਰੀ ਨਦੀ ਕੰਢਿਆਂ ਤੋਂ ਦੂਰ ਰਹਿਣ।",
                "ne": "टिहरी बाँध हिमनदी बहाव बुलेटिन: गंगोत्री क्षेत्रमा हिमनदी पग्लिएर टिहरी जलाशयमा ८९० क्युमेक जलप्रवाह पुगेको छ। तीर्थयात्रीहरू नदी किनारमा नजानुहोला।",
                "ks": "ٹہری ڈیم گلیشیر بلیٹن: گنگوتری گلیشیر پیٹھہٕ آب یوان۔ 890 کیومکس ڈیمس منز داخل گژھان۔",
                "bn": "তেহরি বাঁধ হিমবাহ গলন বুলেটিন: গঙ্গোত্রী হিমবাহ থেকে প্রচুর গলিত জল তেহরি হ্রদে প্রবেশ করছে। নদী তীরের বাসিন্দাদের সতর্ক থাকার পরামর্শ।",
                "bo": "ཏེཧ་རི་ཆུ་རགས་ཀྱི་ཉེན་བརྡ། གངྒོ་ཏྲི་གངས་རི་ཞུ་ནས་ཆུ་རྒྱུན་ཤུགས་ཆེན་འབབ་བཞིན་ཡོད།",
            },
        },
        "chenab_baglihar": {
            "basin_id": "chenab_baglihar",
            "basin_name": "Chenab Basin (Baglihar & Salal Dam Catchment)",
            "state": "Jammu & Kashmir",
            "mountain_range": "Zanskar & Pir Panjal Ranges",
            "drainage_area_sq_km": 29050.0,
            "current_regime": SnowmeltRegime.SEASONAL_SNOWMELT_SURGE,
            "elevation_bands": [
                {
                    "band_id": "ZONE_A",
                    "elevation_range_label": "1,200m - 2,500m AMSL (Lower Chenab Valley)",
                    "elevation_min_m": 1200.0,
                    "elevation_max_m": 2500.0,
                    "zonal_area_sq_km": 5400.0,
                    "snow_cover_area_pct": 5.0,
                    "mean_temperature_c": 17.5,
                    "degree_day_factor_cm_per_deg_c_day": 0.42,
                    "daily_melt_volume_mcm": 2.1,
                },
                {
                    "band_id": "ZONE_B",
                    "elevation_range_label": "2,500m - 3,800m AMSL (Kishtwar & Padder Valleys)",
                    "elevation_min_m": 2500.0,
                    "elevation_max_m": 3800.0,
                    "zonal_area_sq_km": 9850.0,
                    "snow_cover_area_pct": 58.0,
                    "mean_temperature_c": 8.8,
                    "degree_day_factor_cm_per_deg_c_day": 0.55,
                    "daily_melt_volume_mcm": 28.5,
                },
                {
                    "band_id": "ZONE_C",
                    "elevation_range_label": "3,800m - 5,000m AMSL (Zanskar Divide Snowfields)",
                    "elevation_min_m": 3800.0,
                    "elevation_max_m": 5000.0,
                    "zonal_area_sq_km": 10200.0,
                    "snow_cover_area_pct": 82.0,
                    "mean_temperature_c": 3.4,
                    "degree_day_factor_cm_per_deg_c_day": 0.68,
                    "daily_melt_volume_mcm": 36.8,
                },
                {
                    "band_id": "ZONE_D",
                    "elevation_range_label": "> 5,000m AMSL (High Glacial Crests & Nun-Kun)",
                    "elevation_min_m": 5000.0,
                    "elevation_max_m": 6500.0,
                    "zonal_area_sq_km": 3600.0,
                    "snow_cover_area_pct": 95.0,
                    "mean_temperature_c": -3.2,
                    "degree_day_factor_cm_per_deg_c_day": 0.78,
                    "daily_melt_volume_mcm": 3.8,
                },
            ],
            "cryosphere_telemetry": {
                "snow_line_altitude_m": 3400.0,
                "equilibrium_line_altitude_m": 4900.0,
                "freezing_level_isotherm_m": 4550.0,
                "basin_snow_water_equivalent_mm": 260.0,
                "fresh_snow_24h_cm": 0.0,
                "satellite_ndsi_coverage_pct": 92.0,
            },
            "runoff_metrics": {
                "daily_discharge_cumecs": 1180.0,
                "snowmelt_fraction_pct": 68.0,
                "rainfall_contribution_pct": 16.0,
                "baseflow_contribution_pct": 16.0,
                "peak_diurnal_hour_ist": "18:30 IST",
                "peak_diurnal_discharge_cumecs": 1520.0,
                "diurnal_discharge_amplitude_pct": 39.0,
            },
            "hydropower_inflows": [
                {
                    "dam_name": "Baglihar Hydroelectric Project",
                    "river_basin": "Chenab River (Ramban)",
                    "installed_capacity_mw": 900.0,
                    "live_inflow_cumecs": 1150.0,
                    "generation_capacity_utilized_pct": 100.0,
                    "daily_storage_gain_mcm": 15.4,
                    "spillway_clearance_margin_m": 3.2,
                    "inflow_status": HydropowerInflowStatus.OPTIMAL_GENERATION_SURGE,
                },
                {
                    "dam_name": "Salal Dam",
                    "river_basin": "Chenab River (Reasi)",
                    "installed_capacity_mw": 690.0,
                    "live_inflow_cumecs": 1120.0,
                    "generation_capacity_utilized_pct": 100.0,
                    "daily_storage_gain_mcm": 11.2,
                    "spillway_clearance_margin_m": 4.5,
                    "inflow_status": HydropowerInflowStatus.OPTIMAL_GENERATION_SURGE,
                },
            ],
            "riparian_safety_advisory": "Chenab river in full spate due to heavy snowmelt from Zanskar ridges. High turbine discharge at Baglihar and Salal. Riverbank warnings active along Ramban, Doda, and Reasi.",
            "vernacular_bulletins": {
                "en": "CHENAB BASIN SNOWMELT INFLOW BULLETIN: Peak snowmelt surge from Zanskar divide generating 1,180 cumecs in Chenab. Baglihar and Salal operating at 100% capacity. Downstream caution along Ramban and Reasi.",
                "hi": "चिनाब घाटी हिमद्रवण बुलेटिन: जांस्कर पर्वतमाला से भारी बर्फ पिघलने के कारण चिनाब में 1,180 क्यूमेक जलप्रवाह है। बगलिहार व सलाल परियोजनाएं पूर्ण क्षमता पर कार्यरत हैं। नदी के किनारे सावधानी बरतें।",
                "ks": "چناب دریاوس منز سنو میلٹ بلیٹن: زانسکار پہاڑن پیٹھہٕ برف پگھلنے کِنہِ چھُ چناب لبالب بھورمت۔ 1,180 کیومکس پاݨی چھُ دَریاوس منز گژھان۔",
                "pa": "ਚਨਾਬ ਬੇਸਿਨ ਬਰਫ਼ ਪਿਘਲਣ ਬੁਲੇਟਿਨ: ਜ਼ਾਂਸਕਾਰ ਖੇਤਰ ਤੋਂ ਬਰਫ਼ ਪਿਘਲਣ ਕਾਰਨ ਚਨਾਬ ਵਿੱਚ 1,180 ਕਿਊਮਿਕ ਵਹਾਅ। ਬਗਲੀਹਾਰ ਤੇ ਸਲਾਲ ਡੈਮ ਪੂਰੀ ਸਮਰੱਥਾ 'ਤੇ ਚੱਲ ਰਹੇ ਹਨ।",
                "ne": "चनाब नदी जलप्रवाह बुलेटिन: जाँस्कर हिमालबाट हिउँ पग्लिएर चनाब नदीमा ११۸० क्युमेक बहाव पुगेको छ। सतर्कता अपनाउनुहोला।",
                "bn": "চন্দ্রভাগা (চেনাব) তুষারগলন সতর্কতা: চেনাব নদীতে ১,১৮০ কিউমেক তীব্র জলপ্রবাহ। জলবিদ্যুৎ প্রকল্পগুলি পূর্ণ ক্ষমতায় চলছে।",
                "bo": "ཅེ་ནབ་གཙང་པོའི་ཁངས་ཆུ་རྒྱས་པའི་ཉེན་བརྡ། ཆུ་རྒྱུན་ཤུགས་ཆེན་འབབ་བཞིན་ཡོད།",
            },
        },
        "beas_pong": {
            "basin_id": "beas_pong",
            "basin_name": "Beas Basin & Pong Reservoir Catchment",
            "state": "Himachal Pradesh",
            "mountain_range": "Dhauladhar & Pir Panjal Ranges",
            "drainage_area_sq_km": 12560.0,
            "current_regime": SnowmeltRegime.SEASONAL_SNOWMELT_SURGE,
            "elevation_bands": [
                {
                    "band_id": "ZONE_A",
                    "elevation_range_label": "800m - 2,000m AMSL (Kullu & Mandi Valleys)",
                    "elevation_min_m": 800.0,
                    "elevation_max_m": 2000.0,
                    "zonal_area_sq_km": 4200.0,
                    "snow_cover_area_pct": 2.0,
                    "mean_temperature_c": 18.8,
                    "degree_day_factor_cm_per_deg_c_day": 0.36,
                    "daily_melt_volume_mcm": 1.2,
                },
                {
                    "band_id": "ZONE_B",
                    "elevation_range_label": "2,000m - 3,200m AMSL (Solang & Rohtang Slopes)",
                    "elevation_min_m": 2000.0,
                    "elevation_max_m": 3200.0,
                    "zonal_area_sq_km": 3950.0,
                    "snow_cover_area_pct": 46.0,
                    "mean_temperature_c": 11.2,
                    "degree_day_factor_cm_per_deg_c_day": 0.46,
                    "daily_melt_volume_mcm": 18.5,
                },
                {
                    "band_id": "ZONE_C",
                    "elevation_range_label": "3,200m - 4,500m AMSL (Dhauladhar Crests)",
                    "elevation_min_m": 3200.0,
                    "elevation_max_m": 4500.0,
                    "zonal_area_sq_km": 3410.0,
                    "snow_cover_area_pct": 76.0,
                    "mean_temperature_c": 5.2,
                    "degree_day_factor_cm_per_deg_c_day": 0.58,
                    "daily_melt_volume_mcm": 24.2,
                },
                {
                    "band_id": "ZONE_D",
                    "elevation_range_label": "> 4,500m AMSL (Beas Kund & Hanuman Tibba Peaks)",
                    "elevation_min_m": 4500.0,
                    "elevation_max_m": 5930.0,
                    "zonal_area_sq_km": 1000.0,
                    "snow_cover_area_pct": 92.0,
                    "mean_temperature_c": -1.8,
                    "degree_day_factor_cm_per_deg_c_day": 0.70,
                    "daily_melt_volume_mcm": 3.2,
                },
            ],
            "cryosphere_telemetry": {
                "snow_line_altitude_m": 3100.0,
                "equilibrium_line_altitude_m": 4650.0,
                "freezing_level_isotherm_m": 4480.0,
                "basin_snow_water_equivalent_mm": 240.0,
                "fresh_snow_24h_cm": 0.0,
                "satellite_ndsi_coverage_pct": 91.5,
            },
            "runoff_metrics": {
                "daily_discharge_cumecs": 740.0,
                "snowmelt_fraction_pct": 61.0,
                "rainfall_contribution_pct": 21.0,
                "baseflow_contribution_pct": 18.0,
                "peak_diurnal_hour_ist": "17:00 IST",
                "peak_diurnal_discharge_cumecs": 980.0,
                "diurnal_discharge_amplitude_pct": 44.0,
            },
            "hydropower_inflows": [
                {
                    "dam_name": "Pong Dam (Maharana Pratap Sagar)",
                    "river_basin": "Beas River Basin",
                    "installed_capacity_mw": 396.0,
                    "live_inflow_cumecs": 710.0,
                    "generation_capacity_utilized_pct": 94.0,
                    "daily_storage_gain_mcm": 42.0,
                    "spillway_clearance_margin_m": 9.6,
                    "inflow_status": HydropowerInflowStatus.NORMAL_STORAGE_FILL,
                },
            ],
            "riparian_safety_advisory": "Diurnal snowmelt pulse in Beas river between Manali and Pandoh. River crossing near Rohtang base and Solang nallahs strictly prohibited after 15:00 IST.",
            "vernacular_bulletins": {
                "en": "BEAS BASIN SNOWMELT INFLOW BULLETIN: Melting of snowpack in Rohtang and Dhauladhar generating 740 cumecs flow in Beas. Pong Dam storage filling steadily for irrigation canals.",
                "hi": "ब्यास घाटी हिमद्रवण बुलेटिन: रोहतांग और धौलाधार से बर्फ पिघलने से ब्यास नदी में 740 क्यूमेक प्रवाह है। पोंग जलाशय में जल संचयन तेजी से हो रहा है।",
                "pa": "ਬਿਆਸ ਦਰਿਆ ਬਰਫ਼ ਪਿਘਲਣ ਬੁਲੇਟਿਨ: ਰੋਹਤਾਂਗ ਪਾਸ ਨੇੜਿਓਂ ਬਰਫ਼ ਪਿਘਲਣ ਨਾਲ ਬਿਆਸ ਦਰਿਆ ਵਿੱਚ 740 ਕਿਊਮਿਕ ਪਾਣੀ ਆ ਰਿਹਾ ਹੈ। ਪੌਂਗ ਡੈਮ ਭਰ ਰਿਹਾ ਹੈ।",
                "ne": "व्यास नदी बहाव बुलेटिन: रोहतांग क्षेत्रमा हिउँ पग्लिएर व्यास नदीमा ७४० क्युमेक जलप्रवाह पुगेको छ।",
                "ks": "بیاس ویلی سنو میلٹ بلیٹن: پونگ ڈیمس منز چھُ آب جمع گژھان۔",
                "bn": "বিয়াস অববাহিকা তুষারগলন বুলেটিন: রোহতাং গিরিপথ অঞ্চলে তুষার গলে বিয়াস নদীতে ৭৪০ কিউমেক প্রবাহ তৈরি হয়েছে।",
                "bo": "བེའས་གཙང་པོའི་ཁངས་ཆུ་རྒྱས་པའི་ཉེན་བརྡ།",
            },
        },
        "jhelum_uri": {
            "basin_id": "jhelum_uri",
            "basin_name": "Jhelum & Kishanganga Basin (Uri-I & II HEP)",
            "state": "Jammu & Kashmir",
            "mountain_range": "Kashmir Himalaya & Shamshabari",
            "drainage_area_sq_km": 14790.0,
            "current_regime": SnowmeltRegime.TRANSITIONAL_FREEZE_THAW,
            "elevation_bands": [
                {
                    "band_id": "ZONE_A",
                    "elevation_range_label": "1,550m - 2,200m AMSL (Kashmir Valley Plain)",
                    "elevation_min_m": 1550.0,
                    "elevation_max_m": 2200.0,
                    "zonal_area_sq_km": 4900.0,
                    "snow_cover_area_pct": 0.0,
                    "mean_temperature_c": 19.5,
                    "degree_day_factor_cm_per_deg_c_day": 0.35,
                    "daily_melt_volume_mcm": 0.0,
                },
                {
                    "band_id": "ZONE_B",
                    "elevation_range_label": "2,200m - 3,400m AMSL (Gulmarg & Pahalgam Ridges)",
                    "elevation_min_m": 2200.0,
                    "elevation_max_m": 3400.0,
                    "zonal_area_sq_km": 4850.0,
                    "snow_cover_area_pct": 42.0,
                    "mean_temperature_c": 10.5,
                    "degree_day_factor_cm_per_deg_c_day": 0.48,
                    "daily_melt_volume_mcm": 16.2,
                },
                {
                    "band_id": "ZONE_C",
                    "elevation_range_label": "3,400m - 4,500m AMSL (Pir Panjal & Shamshabari)",
                    "elevation_min_m": 3400.0,
                    "elevation_max_m": 4500.0,
                    "zonal_area_sq_km": 3840.0,
                    "snow_cover_area_pct": 74.0,
                    "mean_temperature_c": 4.5,
                    "degree_day_factor_cm_per_deg_c_day": 0.60,
                    "daily_melt_volume_mcm": 22.4,
                },
                {
                    "band_id": "ZONE_D",
                    "elevation_range_label": "> 4,500m AMSL (Kolahoi & Haramukh Peaks)",
                    "elevation_min_m": 4500.0,
                    "elevation_max_m": 5425.0,
                    "zonal_area_sq_km": 1200.0,
                    "snow_cover_area_pct": 94.0,
                    "mean_temperature_c": -1.5,
                    "degree_day_factor_cm_per_deg_c_day": 0.72,
                    "daily_melt_volume_mcm": 3.5,
                },
            ],
            "cryosphere_telemetry": {
                "snow_line_altitude_m": 3200.0,
                "equilibrium_line_altitude_m": 4700.0,
                "freezing_level_isotherm_m": 4500.0,
                "basin_snow_water_equivalent_mm": 220.0,
                "fresh_snow_24h_cm": 0.0,
                "satellite_ndsi_coverage_pct": 93.0,
            },
            "runoff_metrics": {
                "daily_discharge_cumecs": 580.0,
                "snowmelt_fraction_pct": 52.0,
                "rainfall_contribution_pct": 26.0,
                "baseflow_contribution_pct": 22.0,
                "peak_diurnal_hour_ist": "18:00 IST",
                "peak_diurnal_discharge_cumecs": 720.0,
                "diurnal_discharge_amplitude_pct": 32.0,
            },
            "hydropower_inflows": [
                {
                    "dam_name": "Uri-I Hydroelectric Power Plant",
                    "river_basin": "Lower Jhelum River",
                    "installed_capacity_mw": 480.0,
                    "live_inflow_cumecs": 560.0,
                    "generation_capacity_utilized_pct": 96.0,
                    "daily_storage_gain_mcm": 5.0,
                    "spillway_clearance_margin_m": 3.8,
                    "inflow_status": HydropowerInflowStatus.OPTIMAL_GENERATION_SURGE,
                },
                {
                    "dam_name": "Kishanganga HEP",
                    "river_basin": "Gurez Valley / Kishanganga",
                    "installed_capacity_mw": 330.0,
                    "live_inflow_cumecs": 340.0,
                    "generation_capacity_utilized_pct": 100.0,
                    "daily_storage_gain_mcm": 4.2,
                    "spillway_clearance_margin_m": 2.9,
                    "inflow_status": HydropowerInflowStatus.OPTIMAL_GENERATION_SURGE,
                },
            ],
            "riparian_safety_advisory": "Moderate snowmelt runoff passing through Srinagar and Wular lake. Water levels stable at Ram Munshi Bagh and Sangam gauges.",
            "vernacular_bulletins": {
                "en": "JHELUM & KISHANGANGA HYDROLOGY BULLETIN: Moderate snowmelt runoff with total discharge of 580 cumecs. Wular Lake buffering flow. Uri-I and Kishanganga operating at high generation dispatch.",
                "hi": "झेलम व किशनगंगा जलविज्ञान बुलेटिन: पहाड़ों पर बर्फ पिघलने से झेलम में 580 क्यूमेक प्रवाह है। वुलर झील में जलस्तर सामान्य है। उरी परियोजनाएं सुचारू रूप से बिजली उत्पादन कर रही हैं।",
                "ks": "جہلم تہٕ کشن گنگا سنو میلٹ بلیٹن: جہلمس منز چھُ 580 کیومکس آب یوان۔ وولر جھیل چھِ آب سنبھالان۔",
                "pa": "ਜੇਹਲਮ ਅਤੇ ਕਿਸ਼ਨਗੰਗਾ ਬੁਲੇਟਿਨ: 580 ਕਿਊਮਿਕ ਪਾਣੀ ਦਾ ਵਹਾਅ ਦਰਜ। ਉੜੀ ਪਾਵਰ ਪਲਾਂਟ ਪੂਰੀ ਸਮਰੱਥਾ 'ਤੇ ਚੱਲ ਰਿਹਾ ਹੈ।",
                "ne": "झेलम तथा किशनगंगा बहाव बुलेटिन: हिउँ पग्लिएर ५८० क्युमेक जलপ্রवाह पुगेको छ।",
                "bn": "ঝেলম ও কিষানগঙ্গা জলপ্রবাহ বুলেটিন: ৫৮০ কিউমেক জলপ্রবাহ রেকর্ড করা হয়েছে। উরি বিদ্যুৎ প্রকল্প পূর্ণ সচল।",
                "bo": "ཇེ་ལམ་གཙང་པོའི་ཆུ་རྒྱུན་བདེ་འཇགས།",
            },
        },
        "teesta_v": {
            "basin_id": "teesta_v",
            "basin_name": "Teesta Basin & Teesta-V HEP Catchment",
            "state": "Sikkim",
            "mountain_range": "Eastern Himalaya (Kanchenjunga Massif)",
            "drainage_area_sq_km": 12540.0,
            "current_regime": SnowmeltRegime.RAIN_ON_SNOW_BURST,
            "elevation_bands": [
                {
                    "band_id": "ZONE_A",
                    "elevation_range_label": "300m - 2,000m AMSL (Teesta Gorge & Foothills)",
                    "elevation_min_m": 300.0,
                    "elevation_max_m": 2000.0,
                    "zonal_area_sq_km": 3600.0,
                    "snow_cover_area_pct": 0.0,
                    "mean_temperature_c": 22.5,
                    "degree_day_factor_cm_per_deg_c_day": 0.40,
                    "daily_melt_volume_mcm": 0.0,
                },
                {
                    "band_id": "ZONE_B",
                    "elevation_range_label": "2,000m - 3,500m AMSL (Lachen & Lachung Valleys)",
                    "elevation_min_m": 2000.0,
                    "elevation_max_m": 3500.0,
                    "zonal_area_sq_km": 3840.0,
                    "snow_cover_area_pct": 28.0,
                    "mean_temperature_c": 12.8,
                    "degree_day_factor_cm_per_deg_c_day": 0.52,
                    "daily_melt_volume_mcm": 14.8,
                },
                {
                    "band_id": "ZONE_C",
                    "elevation_range_label": "3,500m - 5,000m AMSL (Zemu Glacier Moraines)",
                    "elevation_min_m": 3500.0,
                    "elevation_max_m": 5000.0,
                    "zonal_area_sq_km": 3300.0,
                    "snow_cover_area_pct": 72.0,
                    "mean_temperature_c": 6.2,
                    "degree_day_factor_cm_per_deg_c_day": 0.76,
                    "daily_melt_volume_mcm": 26.5,
                },
                {
                    "band_id": "ZONE_D",
                    "elevation_range_label": "> 5,000m AMSL (Kanchenjunga Glacial Icefield)",
                    "elevation_min_m": 5000.0,
                    "elevation_max_m": 8586.0,
                    "zonal_area_sq_km": 1800.0,
                    "snow_cover_area_pct": 98.0,
                    "mean_temperature_c": 0.5,
                    "degree_day_factor_cm_per_deg_c_day": 0.88,
                    "daily_melt_volume_mcm": 11.2,
                },
            ],
            "cryosphere_telemetry": {
                "snow_line_altitude_m": 4100.0,
                "equilibrium_line_altitude_m": 5300.0,
                "freezing_level_isotherm_m": 5150.0,
                "basin_snow_water_equivalent_mm": 190.0,
                "fresh_snow_24h_cm": 0.0,
                "satellite_ndsi_coverage_pct": 89.0,
            },
            "runoff_metrics": {
                "daily_discharge_cumecs": 960.0,
                "snowmelt_fraction_pct": 46.0,
                "rainfall_contribution_pct": 38.0,
                "baseflow_contribution_pct": 16.0,
                "peak_diurnal_hour_ist": "19:00 IST",
                "peak_diurnal_discharge_cumecs": 1350.0,
                "diurnal_discharge_amplitude_pct": 48.0,
            },
            "hydropower_inflows": [
                {
                    "dam_name": "Teesta-V Hydroelectric Project",
                    "river_basin": "Teesta River (Dikchu)",
                    "installed_capacity_mw": 510.0,
                    "live_inflow_cumecs": 920.0,
                    "generation_capacity_utilized_pct": 100.0,
                    "daily_storage_gain_mcm": 8.5,
                    "spillway_clearance_margin_m": 2.4,
                    "inflow_status": HydropowerInflowStatus.SPILLWAY_DISCHARGE_WARNING,
                },
            ],
            "riparian_safety_advisory": "Rain-on-snow event combined with rapid Zemu glacier ablation. Water levels rising swiftly in Teesta gorge. Low-lying areas along Singtam and Rangpo put on high riparian alert.",
            "vernacular_bulletins": {
                "en": "TEESTA BASIN HIGH-DISCHARGE BULLETIN: Combined monsoon rainfall and Zemu glacier ablation producing 960 cumecs surge in Teesta river. Teesta-V dam approaching spillway threshold. Singtam and Rangpo riparian zones on alert.",
                "ne": "टिस्टा जलाधार उच्च बहाव चेतावनी: वर्षा र जेमु हिमनदी पग्लिएर टिस्टा नदीमा ९६০ क्युमेकको ठूलो बाढी आएको छ। सिङताम र राङ्पो क्षेत्रका बासिन्दा सतर्क रहनुहोला।",
                "hi": "तीस्ता घाटी जलप्रवाह बुलेटिन: वर्षा और जेमू ग्लेशियर के पिघलने से तीस्ता में 960 क्यूमेक का तेज बहाव है। तीस्ता-V बांध से पानी छोड़े जाने की संभावना है। सिंगताम व रंगपो में सतर्कता बरतें।",
                "bn": "তিস্তা অববাহিকা উচ্চ জলপ্রবাহ সতর্কতা: ভারী বৃষ্টি এবং জেমু হিমবাহের দ্রুত গলনে তিস্তা নদীতে ৯৬০ কিউমেক তীব্র প্রবাহ। সিংতাম ও রংপো সংলগ্ন নদী তীরবর্তী বাসিন্দাদের সতর্ক থাকার নির্দেশ।",
                "pa": "ਤੀਸਤਾ ਬੇਸਿਨ ਬੁਲੇਟਿਨ: ਮੀਂਹ ਅਤੇ ਗਲੇਸ਼ੀਅਰ ਪਿਘਲਣ ਕਾਰਨ ਤੀਸਤਾ ਵਿੱਚ 960 ਕਿਊਮਿਕ ਤੇਜ਼ ਵਹਾਅ।",
                "ks": "تیستا دریاوس منز آبُک تیز بہاؤ۔",
                "bo": "ཏཱིསྟ་གཙང་པོའི་ཆུ་ལོག་ཉེན་བརྡ། ཆར་པ་དང་གངས་ཆུ་འདྲེས་ནས་ཆུ་རྒྱུན་ཤིན་ཏུ་ཆེན་པོ་འབབ་བཞིན་ཡོད།",
            },
        },
        "subansiri_lower": {
            "basin_id": "subansiri_lower",
            "basin_name": "Subansiri Basin (Subansiri Lower HEP Catchment)",
            "state": "Arunachal Pradesh & Assam",
            "mountain_range": "Eastern Himalaya & Trans-Himalayan Plateau",
            "drainage_area_sq_km": 32600.0,
            "current_regime": SnowmeltRegime.RAIN_ON_SNOW_BURST,
            "elevation_bands": [
                {
                    "band_id": "ZONE_A",
                    "elevation_range_label": "150m - 1,800m AMSL (Assam-Arunachal Foothills)",
                    "elevation_min_m": 150.0,
                    "elevation_max_m": 1800.0,
                    "zonal_area_sq_km": 7200.0,
                    "snow_cover_area_pct": 0.0,
                    "mean_temperature_c": 24.0,
                    "degree_day_factor_cm_per_deg_c_day": 0.40,
                    "daily_melt_volume_mcm": 0.0,
                },
                {
                    "band_id": "ZONE_B",
                    "elevation_range_label": "1,800m - 3,500m AMSL (Sub-Himalayan Valleys)",
                    "elevation_min_m": 1800.0,
                    "elevation_max_m": 3500.0,
                    "zonal_area_sq_km": 10500.0,
                    "snow_cover_area_pct": 18.0,
                    "mean_temperature_c": 13.5,
                    "degree_day_factor_cm_per_deg_c_day": 0.50,
                    "daily_melt_volume_mcm": 22.4,
                },
                {
                    "band_id": "ZONE_C",
                    "elevation_range_label": "3,500m - 4,800m AMSL (High Glaciated Ridges)",
                    "elevation_min_m": 3500.0,
                    "elevation_max_m": 4800.0,
                    "zonal_area_sq_km": 9400.0,
                    "snow_cover_area_pct": 65.0,
                    "mean_temperature_c": 5.8,
                    "degree_day_factor_cm_per_deg_c_day": 0.68,
                    "daily_melt_volume_mcm": 38.6,
                },
                {
                    "band_id": "ZONE_D",
                    "elevation_range_label": "> 4,800m AMSL (Tibetan Plateau Headwaters)",
                    "elevation_min_m": 4800.0,
                    "elevation_max_m": 6200.0,
                    "zonal_area_sq_km": 5500.0,
                    "snow_cover_area_pct": 92.0,
                    "mean_temperature_c": -0.8,
                    "degree_day_factor_cm_per_deg_c_day": 0.82,
                    "daily_melt_volume_mcm": 15.2,
                },
            ],
            "cryosphere_telemetry": {
                "snow_line_altitude_m": 3850.0,
                "equilibrium_line_altitude_m": 5050.0,
                "freezing_level_isotherm_m": 5100.0,
                "basin_snow_water_equivalent_mm": 205.0,
                "fresh_snow_24h_cm": 0.0,
                "satellite_ndsi_coverage_pct": 90.0,
            },
            "runoff_metrics": {
                "daily_discharge_cumecs": 2150.0,
                "snowmelt_fraction_pct": 42.0,
                "rainfall_contribution_pct": 44.0,
                "baseflow_contribution_pct": 14.0,
                "peak_diurnal_hour_ist": "19:30 IST",
                "peak_diurnal_discharge_cumecs": 2850.0,
                "diurnal_discharge_amplitude_pct": 46.0,
            },
            "hydropower_inflows": [
                {
                    "dam_name": "Subansiri Lower Hydroelectric Project",
                    "river_basin": "Subansiri (Gerukamukh)",
                    "installed_capacity_mw": 2000.0,
                    "live_inflow_cumecs": 2080.0,
                    "generation_capacity_utilized_pct": 100.0,
                    "daily_storage_gain_mcm": 78.0,
                    "spillway_clearance_margin_m": 5.2,
                    "inflow_status": HydropowerInflowStatus.OPTIMAL_GENERATION_SURGE,
                },
            ],
            "riparian_safety_advisory": "Subansiri river experiencing monsoon rainfall combined with high plateau snowmelt. Flash runoff alert in Lakhimpur and Dhemaji downstream districts of Assam.",
            "vernacular_bulletins": {
                "en": "SUBANSIRI HYDROLOGICAL INFLOW BULLETIN: Trans-Himalayan plateau snowmelt and heavy monsoon rain driving 2,150 cumecs inflow into Subansiri Lower dam. Dhemaji and Lakhimpur riparian flood watch activated.",
                "hi": "सुबनसिरी घाटी जलप्रवाह बुलेटिन: पठारी बर्फ पिघलने और मानसूनी बारिश से सुबनसिरी में 2,150 क्यूमेक प्रवाह दर्ज। असम के धेमाजी व लखीमपुर जिलों में बाढ़ की निगरानी जारी।",
                "bn": "সুবনসিরি নদী জলপ্রবাহ বুলেটিন: তিব্বতীয় মালভূমির বরফ গলন ও ভারী বৃষ্টিতে সুবনসিরি নদীতে ২,১৫০ কিউমেক তীব্র জলপ্রবাহ। ধেমাজি ও লখিমপুর জেলায় সতর্কতা।",
                "ne": "सुबनसिरी नदी बहाव बुलेटिन: हिउँ पग्लिएर र वर्षाका कारण सुबनसिरीमा २१५० क्युमेक जलप्रवाह पुगेको छ। असमको धेमाजीमा सतर्कता।",
                "pa": "ਸੁਬਨਸਿਰੀ ਬੇਸਿਨ ਬੁਲੇਟਿਨ: 2,150 ਕਿਊਮਿਕ ਪਾਣੀ ਦਾ ਵੱਡਾ ਵਹਾਅ ਦਰਜ।",
                "ks": "سبنسری دریاوس منز 2,150 کیومکس آب۔",
                "bo": "སུ་བན་སི་རི་གཙང་པོའི་ཆུ་རྒྱུན་ཉེན་བརྡ།",
            },
        },
    }

    @classmethod
    def get_assessment(cls, basin_id: Optional[str] = None) -> SnowmeltRunoffResponse:
        """Fetch hydro-meteorological snowmelt assessment for a given Himalayan basin."""
        selected_id = basin_id if basin_id in cls._BASIN_REGISTRY else "satluj_bhakra"
        raw_basin = cls._BASIN_REGISTRY[selected_id]

        elevation_bands = [
            ElevationZonalBand(**b) for b in raw_basin["elevation_bands"]
        ]
        cryo = SnowpackCryosphereTelemetry(**raw_basin["cryosphere_telemetry"])
        runoff = CatchmentRunoffMetrics(**raw_basin["runoff_metrics"])
        hydropower = [
            DownstreamHydropowerInflow(**h) for h in raw_basin["hydropower_inflows"]
        ]

        current_basin = SnowmeltBasin(
            basin_id=raw_basin["basin_id"],
            basin_name=raw_basin["basin_name"],
            state=raw_basin["state"],
            mountain_range=raw_basin["mountain_range"],
            drainage_area_sq_km=raw_basin["drainage_area_sq_km"],
            current_regime=raw_basin["current_regime"],
            elevation_bands=elevation_bands,
            cryosphere_telemetry=cryo,
            runoff_metrics=runoff,
            hydropower_inflows=hydropower,
            riparian_safety_advisory=raw_basin["riparian_safety_advisory"],
            vernacular_bulletins=raw_basin["vernacular_bulletins"],
        )

        all_basins: List[BasinSummary] = []
        for b_id, b_data in cls._BASIN_REGISTRY.items():
            first_status = HydropowerInflowStatus.OPTIMAL_GENERATION_SURGE
            if b_data.get("hydropower_inflows"):
                first_status = b_data["hydropower_inflows"][0]["inflow_status"]

            all_basins.append(
                BasinSummary(
                    basin_id=b_data["basin_id"],
                    basin_name=b_data["basin_name"],
                    state=b_data["state"],
                    river_system=b_data["mountain_range"],
                    daily_discharge_cumecs=b_data["runoff_metrics"]["daily_discharge_cumecs"],
                    snowmelt_fraction_pct=b_data["runoff_metrics"]["snowmelt_fraction_pct"],
                    inflow_status=first_status,
                )
            )

        return SnowmeltRunoffResponse(
            basin_id=current_basin.basin_id,
            basin_name=current_basin.basin_name,
            state=current_basin.state,
            current_basin=current_basin,
            all_basins=all_basins,
            last_updated_utc=datetime.now(timezone.utc).isoformat(),
            data_source="IMD Mountain Weather Division, CWC (Ministry of Jal Shakti), DRDO-DGRE & NRSC-ISRO",
        )
